-- Research-only LOGGED tables, never included by production schema.sql.
-- The runner must first verify a disposable ghost_compact_storage_validation_*
-- database identity. This file never creates/drops a database or runtime table.
CREATE SCHEMA IF NOT EXISTS ghost_compact_probe;

CREATE TABLE ghost_compact_probe.compact_json (
    copy_id INTEGER NOT NULL CHECK (copy_id >= 0),
    run_id TEXT COLLATE "C" NOT NULL,
    decision_id TEXT COLLATE "C" NOT NULL,
    retention_created_ms BIGINT NOT NULL CHECK (retention_created_ms >= 0),
    target_source_timestamps_ms BIGINT[] NOT NULL CHECK (cardinality(target_source_timestamps_ms) <= 6),
    terminal BOOLEAN NOT NULL,
    probe_revision INTEGER NOT NULL DEFAULT 0 CHECK (probe_revision >= 0),
    summarized_revision INTEGER CHECK (summarized_revision >= 0),
    record_json TEXT NOT NULL,
    PRIMARY KEY (copy_id, run_id, decision_id)
);
CREATE INDEX compact_json_retention_idx ON ghost_compact_probe.compact_json
    (retention_created_ms, copy_id, run_id, decision_id);
-- Same target-lookup capability as the typed child B-tree, different physical
-- index representation; both costs count in the measured layout allocation.
CREATE INDEX compact_json_targets_idx ON ghost_compact_probe.compact_json
    USING GIN (target_source_timestamps_ms);

CREATE TABLE ghost_compact_probe.decision (
    copy_id INTEGER NOT NULL CHECK (copy_id >= 0),
    run_id TEXT COLLATE "C" NOT NULL,
    decision_id TEXT COLLATE "C" NOT NULL,
    retention_created_ms BIGINT NOT NULL CHECK (retention_created_ms >= 0),
    terminal BOOLEAN NOT NULL,
    probe_revision INTEGER NOT NULL DEFAULT 0 CHECK (probe_revision >= 0),
    summarized_revision INTEGER CHECK (summarized_revision >= 0),
    schema_version SMALLINT NOT NULL CHECK (schema_version = 1),
    compact_sha256 BYTEA NOT NULL CHECK (octet_length(compact_sha256) = 32),
    created_ms BIGINT NOT NULL,
    decision_wall_ns BIGINT NOT NULL,
    decision_monotonic_ns BIGINT NOT NULL,
    record_version BIGINT NOT NULL,
    frozen_sha256 BYTEA NOT NULL CHECK (octet_length(frozen_sha256) = 32),
    state_sha256 BYTEA NOT NULL CHECK (octet_length(state_sha256) = 32),
    attempted_payload_sha256 BYTEA CHECK (octet_length(attempted_payload_sha256) = 32),
    model_version TEXT NOT NULL,
    runtime_version TEXT NOT NULL,
    contract_version INTEGER NOT NULL,
    publication_eligibility_policy TEXT NOT NULL,
    campaign_start_ms BIGINT NOT NULL,
    included_sequence BIGINT NOT NULL,
    computation_completed_wall_ns BIGINT NOT NULL,
    computation_completed_monotonic_ns BIGINT NOT NULL,
    valid_until_wall_ns BIGINT NOT NULL,
    publication_status TEXT NOT NULL,
    eligibility_checked_wall_ns BIGINT,
    eligibility_checked_monotonic_ns BIGINT,
    global_reasons TEXT[] NOT NULL,
    causality_invalid BOOLEAN NOT NULL,
    shutdown TEXT,
    restart_reconciled BOOLEAN NOT NULL,
    publication_restart_outcome TEXT,
    gap_count BIGINT,
    spot_reconnect_status TEXT,
    spot_reconnect_reason TEXT,
    intent_wall_ns BIGINT,
    intent_monotonic_ns BIGINT,
    attempt_wall_ns BIGINT,
    attempt_monotonic_ns BIGINT,
    ack_wall_ns BIGINT,
    ack_monotonic_ns BIGINT,
    policy_enabled BOOLEAN NOT NULL,
    policy_source_max_age_ms INTEGER NOT NULL,
    policy_receipt_max_age_ms INTEGER NOT NULL,
    policy_max_carry_ms INTEGER NOT NULL,
    policy_history_ms INTEGER NOT NULL,
    policy_max_events INTEGER NOT NULL,
    policy_spot_reconnect_max_gap_ms INTEGER NOT NULL,
    current_spot_value NUMERIC(38,18),
    current_spot_source_timestamp_ms BIGINT,
    current_spot_received_wall_ns BIGINT,
    current_spot_received_monotonic_ns BIGINT,
    current_spot_sequence BIGINT,
    current_spot_event_id TEXT,
    current_spot_window_s SMALLINT,
    current_twap_value NUMERIC(38,18),
    current_twap_source_timestamp_ms BIGINT,
    current_twap_received_wall_ns BIGINT,
    current_twap_received_monotonic_ns BIGINT,
    current_twap_sequence BIGINT,
    current_twap_event_id TEXT,
    current_twap_window_s SMALLINT,
    PRIMARY KEY (copy_id, run_id, decision_id)
);
CREATE INDEX decision_retention_idx ON ghost_compact_probe.decision
    (retention_created_ms, copy_id, run_id, decision_id);

CREATE TABLE ghost_compact_probe.horizon (
    copy_id INTEGER NOT NULL CHECK (copy_id >= 0),
    run_id TEXT COLLATE "C" NOT NULL,
    decision_id TEXT COLLATE "C" NOT NULL,
    horizon_s SMALLINT NOT NULL CHECK (horizon_s IN (1,2,3,5,10,30)),
    probe_revision INTEGER NOT NULL DEFAULT 0 CHECK (probe_revision >= 0),
    target_source_timestamp_ms BIGINT,
    forecast_price NUMERIC(38,18),
    quality TEXT NOT NULL,
    max_interior_carry_ms INTEGER NOT NULL,
    reasons TEXT[] NOT NULL,
    attempted_eligible BOOLEAN NOT NULL,
    exclusion_reasons TEXT[] NOT NULL,
    estimated_arrival_wall_ns BIGINT,
    estimated_remaining_ns BIGINT,
    target_status TEXT NOT NULL,
    conflicted BOOLEAN NOT NULL,
    clock_anomaly BOOLEAN NOT NULL,
    late_missing BOOLEAN NOT NULL,
    error NUMERIC(38,18),
    persistence_error NUMERIC(38,18),
    eta_error_ns BIGINT,
    confirmed_redis_lead_ns BIGINT,
    count_observed SMALLINT NOT NULL CHECK (count_observed >= 0),
    count_carried SMALLINT NOT NULL CHECK (count_carried >= 0),
    count_pending SMALLINT NOT NULL CHECK (count_pending >= 0),
    count_future SMALLINT NOT NULL CHECK (count_future >= 0),
    count_missing SMALLINT NOT NULL CHECK (count_missing >= 0),
    first_event_value NUMERIC(38,18),
    first_event_source_timestamp_ms BIGINT,
    first_event_received_wall_ns BIGINT,
    first_event_received_monotonic_ns BIGINT,
    first_event_sequence BIGINT,
    first_event_event_id TEXT,
    first_event_window_s SMALLINT,
    first_late_event_value NUMERIC(38,18),
    first_late_event_source_timestamp_ms BIGINT,
    first_late_event_received_wall_ns BIGINT,
    first_late_event_received_monotonic_ns BIGINT,
    first_late_event_sequence BIGINT,
    first_late_event_event_id TEXT,
    first_late_event_window_s SMALLINT,
    first_conflicting_event_value NUMERIC(38,18),
    first_conflicting_event_source_timestamp_ms BIGINT,
    first_conflicting_event_received_wall_ns BIGINT,
    first_conflicting_event_received_monotonic_ns BIGINT,
    first_conflicting_event_sequence BIGINT,
    first_conflicting_event_event_id TEXT,
    first_conflicting_event_window_s SMALLINT,
    PRIMARY KEY (copy_id, run_id, decision_id, horizon_s),
    FOREIGN KEY (copy_id, run_id, decision_id)
        REFERENCES ghost_compact_probe.decision (copy_id, run_id, decision_id) ON DELETE CASCADE,
    CHECK (count_observed + count_carried + count_pending + count_future + count_missing = 60)
);
CREATE INDEX horizon_target_idx ON ghost_compact_probe.horizon
    (target_source_timestamp_ms, copy_id, run_id, decision_id, horizon_s);
